// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: companies.sql

package db

import (
	"context"
)

const countCompanies = `-- name: CountCompanies :one
SELECT count(*)
FROM companies
`

func (q *Queries) CountCompanies(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCompanies)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCompany = `-- name: GetCompany :one
SELECT slug, name, created_at, updated_at
FROM companies
WHERE slug = $1
`

func (q *Queries) GetCompany(ctx context.Context, slug string) (Company, error) {
	row := q.db.QueryRow(ctx, getCompany, slug)
	var i Company
	err := row.Scan(
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCompanies = `-- name: ListCompanies :many
SELECT c.slug, c.name, count(j.company_slug) AS job_count
FROM companies c
LEFT JOIN jobs j ON j.company_slug = c.slug
GROUP BY c.slug, c.name
ORDER BY c.name
LIMIT $1 OFFSET $2
`

type ListCompaniesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListCompaniesRow struct {
	Slug     string `json:"slug"`
	Name     string `json:"name"`
	JobCount int64  `json:"job_count"`
}

// Catalog page: companies with their job counts. The job count is computed on
// the fly (no denormalized counter yet). This is the one acknowledged place a
// join to jobs is acceptable; LEFT JOIN keeps companies with zero jobs visible.
func (q *Queries) ListCompanies(ctx context.Context, arg ListCompaniesParams) ([]ListCompaniesRow, error) {
	rows, err := q.db.Query(ctx, listCompanies, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompaniesRow{}
	for rows.Next() {
		var i ListCompaniesRow
		if err := rows.Scan(&i.Slug, &i.Name, &i.JobCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
