// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: learned_domains.sql

package db

import (
	"context"
)

const observeLearnedDomain = `-- name: ObserveLearnedDomain :one
INSERT INTO learned_ats_domains (domain, confident_hits)
VALUES ($1, 1)
ON CONFLICT (domain) DO UPDATE
  SET confident_hits = learned_ats_domains.confident_hits + 1,
      last_seen_at = now()
RETURNING confident_hits
`

// Record one confident job-mail sighting for a sender domain, returning its running
// count. The classifier calls this whenever it confidently labels an email as
// application mail, so a recurring unknown ATS domain accrues hits toward promotion.
func (q *Queries) ObserveLearnedDomain(ctx context.Context, domain string) (int32, error) {
	row := q.db.QueryRow(ctx, observeLearnedDomain, domain)
	var confident_hits int32
	err := row.Scan(&confident_hits)
	return confident_hits, err
}

const promotedDomains = `-- name: PromotedDomains :many
SELECT domain
FROM learned_ats_domains
WHERE confident_hits >= $1::int
ORDER BY domain
`

// Domains whose confident-hit count has reached the promotion threshold; the sync
// worker unions these into the Gmail search query.
func (q *Queries) PromotedDomains(ctx context.Context, threshold int32) ([]string, error) {
	rows, err := q.db.Query(ctx, promotedDomains, threshold)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var domain string
		if err := rows.Scan(&domain); err != nil {
			return nil, err
		}
		items = append(items, domain)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
