// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Company struct {
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Job struct {
	ID          int64              `json:"id"`
	Source      string             `json:"source"`
	ExternalID  string             `json:"external_id"`
	URL         string             `json:"url"`
	Title       string             `json:"title"`
	Company     string             `json:"company"`
	Location    string             `json:"location"`
	Remote      bool               `json:"remote"`
	Description string             `json:"description"`
	PostedAt    pgtype.Timestamptz `json:"posted_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CompanySlug string             `json:"company_slug"`
}
