// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: telegram_posts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimTelegramPosts = `-- name: ClaimTelegramPosts :many
WITH claimable AS (
    SELECT channel, msg_id
    FROM telegram_posts
    WHERE extracted_at IS NULL
      AND failed_at IS NULL
      AND (claimed_at IS NULL
           OR claimed_at < now() - make_interval(secs => $1::int))
    ORDER BY posted_at
    FOR UPDATE SKIP LOCKED
    LIMIT $2
)
UPDATE telegram_posts p
SET claimed_at = now()
FROM claimable c
WHERE p.channel = c.channel AND p.msg_id = c.msg_id
RETURNING p.channel, p.msg_id, p.text, p.posted_at
`

type ClaimTelegramPostsParams struct {
	LeaseSeconds int32 `json:"lease_seconds"`
	BatchSize    int32 `json:"batch_size"`
}

type ClaimTelegramPostsRow struct {
	Channel  string             `json:"channel"`
	MsgID    int64              `json:"msg_id"`
	Text     string             `json:"text"`
	PostedAt pgtype.Timestamptz `json:"posted_at"`
}

// Claim a batch of pending posts by stamping claimed_at. SKIP LOCKED lets
// concurrent workers take disjoint rows; the lease predicate reclaims posts whose
// worker died (stale claimed_at), so no separate reaper process is needed.
// Oldest post first so a backlog drains in posting order.
func (q *Queries) ClaimTelegramPosts(ctx context.Context, arg ClaimTelegramPostsParams) ([]ClaimTelegramPostsRow, error) {
	rows, err := q.db.Query(ctx, claimTelegramPosts, arg.LeaseSeconds, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimTelegramPostsRow{}
	for rows.Next() {
		var i ClaimTelegramPostsRow
		if err := rows.Scan(
			&i.Channel,
			&i.MsgID,
			&i.Text,
			&i.PostedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTelegramPost = `-- name: InsertTelegramPost :execrows
INSERT INTO telegram_posts (channel, msg_id, text, posted_at, extracted_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (channel, msg_id) DO NOTHING
`

type InsertTelegramPostParams struct {
	Channel     string             `json:"channel"`
	MsgID       int64              `json:"msg_id"`
	Text        string             `json:"text"`
	PostedAt    pgtype.Timestamptz `json:"posted_at"`
	ExtractedAt pgtype.Timestamptz `json:"extracted_at"`
}

// Crawl write path: store a fetched post once. ON CONFLICT DO NOTHING makes
// re-crawling idempotent — a stored post (pending, done, or dead-lettered) is
// never reset. extracted_at is non-NULL when the ingest prefilter already
// decided the post holds no vacancy, so it is recorded but never queued.
func (q *Queries) InsertTelegramPost(ctx context.Context, arg InsertTelegramPostParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertTelegramPost,
		arg.Channel,
		arg.MsgID,
		arg.Text,
		arg.PostedAt,
		arg.ExtractedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markTelegramPostExtracted = `-- name: MarkTelegramPostExtracted :exec
UPDATE telegram_posts
SET extracted_at = now()
WHERE channel = $1 AND msg_id = $2
`

type MarkTelegramPostExtractedParams struct {
	Channel string `json:"channel"`
	MsgID   int64  `json:"msg_id"`
}

// Completion: the post was processed (jobs written, or no vacancy found). Run in
// the same transaction as the extracted jobs' UpsertJob calls.
func (q *Queries) MarkTelegramPostExtracted(ctx context.Context, arg MarkTelegramPostExtractedParams) error {
	_, err := q.db.Exec(ctx, markTelegramPostExtracted, arg.Channel, arg.MsgID)
	return err
}

const recordTelegramPostFailure = `-- name: RecordTelegramPostFailure :one
UPDATE telegram_posts
SET attempts   = attempts + 1,
    last_error = $1,
    failed_at  = CASE
                     WHEN attempts + 1 >= $2::int THEN now()
                     ELSE NULL
                 END
WHERE channel = $3 AND msg_id = $4
RETURNING attempts, failed_at
`

type RecordTelegramPostFailureParams struct {
	LastError   string `json:"last_error"`
	MaxAttempts int32  `json:"max_attempts"`
	Channel     string `json:"channel"`
	MsgID       int64  `json:"msg_id"`
}

type RecordTelegramPostFailureRow struct {
	Attempts int32              `json:"attempts"`
	FailedAt pgtype.Timestamptz `json:"failed_at"`
}

// Count a failed attempt: bump attempts, record the error, and dead-letter (set
// failed_at) once attempts reach the max. The lease (claimed_at) is intentionally
// left in place — its expiry gates the retry to a later run and doubles as the
// crash reaper, so a failed post is never reprocessed within the same run.
func (q *Queries) RecordTelegramPostFailure(ctx context.Context, arg RecordTelegramPostFailureParams) (RecordTelegramPostFailureRow, error) {
	row := q.db.QueryRow(ctx, recordTelegramPostFailure,
		arg.LastError,
		arg.MaxAttempts,
		arg.Channel,
		arg.MsgID,
	)
	var i RecordTelegramPostFailureRow
	err := row.Scan(&i.Attempts, &i.FailedAt)
	return i, err
}
