// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_job_analysis.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRecentUserJobAnalyses = `-- name: CountRecentUserJobAnalyses :one
SELECT count(*)
FROM user_job_analysis
WHERE user_id = $1 AND created_at >= $2
`

type CountRecentUserJobAnalysesParams struct {
	UserID    int64              `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// How many distinct jobs the caller first analyzed within the window (created_at is the
// first-analysis time — see UpsertUserJobAnalysis). This is the fit-analysis quota
// meter: the PK guarantees one row per (user, job), so the row count is the distinct-job
// count. A recompute does not add a row, so it never consumes quota.
func (q *Queries) CountRecentUserJobAnalyses(ctx context.Context, arg CountRecentUserJobAnalysesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentUserJobAnalyses, arg.UserID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserJobAnalysis = `-- name: GetUserJobAnalysis :one
SELECT analysis, model, cv_uploaded_at, job_content_hash, created_at
FROM user_job_analysis
WHERE user_id = $1 AND job_id = $2
`

type GetUserJobAnalysisParams struct {
	UserID int64 `json:"user_id"`
	JobID  int64 `json:"job_id"`
}

type GetUserJobAnalysisRow struct {
	Analysis       []byte             `json:"analysis"`
	Model          string             `json:"model"`
	CvUploadedAt   pgtype.Timestamptz `json:"cv_uploaded_at"`
	JobContentHash pgtype.Text        `json:"job_content_hash"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

// The caller's cached fit analysis for one job, with the staleness stamps it was
// computed against. No row means the pair was never analyzed (the handler serves a
// null analysis, no LLM call). The handler compares cv_uploaded_at / job_content_hash
// to the live CV upload time and job content_hash to decide the stale flag.
func (q *Queries) GetUserJobAnalysis(ctx context.Context, arg GetUserJobAnalysisParams) (GetUserJobAnalysisRow, error) {
	row := q.db.QueryRow(ctx, getUserJobAnalysis, arg.UserID, arg.JobID)
	var i GetUserJobAnalysisRow
	err := row.Scan(
		&i.Analysis,
		&i.Model,
		&i.CvUploadedAt,
		&i.JobContentHash,
		&i.CreatedAt,
	)
	return i, err
}

const upsertUserJobAnalysis = `-- name: UpsertUserJobAnalysis :exec
INSERT INTO user_job_analysis (user_id, job_id, analysis, model, cv_uploaded_at, job_content_hash, created_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT (user_id, job_id) DO UPDATE
SET analysis         = EXCLUDED.analysis,
    model            = EXCLUDED.model,
    cv_uploaded_at   = EXCLUDED.cv_uploaded_at,
    job_content_hash = EXCLUDED.job_content_hash
`

type UpsertUserJobAnalysisParams struct {
	UserID         int64              `json:"user_id"`
	JobID          int64              `json:"job_id"`
	Analysis       []byte             `json:"analysis"`
	Model          string             `json:"model"`
	CvUploadedAt   pgtype.Timestamptz `json:"cv_uploaded_at"`
	JobContentHash pgtype.Text        `json:"job_content_hash"`
}

// Create-or-replace the cached analysis for a (user, job). The composite PRIMARY KEY
// makes it idempotent: a recompute overwrites the analysis, model, and both staleness
// stamps. created_at is deliberately NOT re-bumped on conflict, so it records the
// FIRST-analysis time — the fit-analysis quota counts distinct jobs a user first
// analyzed within a rolling window, and a recompute must not re-age its row into it.
// analysis is the sanitized jobfit.Analysis JSON.
func (q *Queries) UpsertUserJobAnalysis(ctx context.Context, arg UpsertUserJobAnalysisParams) error {
	_, err := q.db.Exec(ctx, upsertUserJobAnalysis,
		arg.UserID,
		arg.JobID,
		arg.Analysis,
		arg.Model,
		arg.CvUploadedAt,
		arg.JobContentHash,
	)
	return err
}
